version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db_padrao
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql

    restart: always

volumes:
  postgres_data:
